/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bel.log4j.bug

import groovy.util.logging.Log4j2
import org.apache.log4j.Logger
import org.apache.log4j.xml.DOMConfigurator
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Marker
import org.apache.logging.log4j.MarkerManager

@Log4j2
class App {

    //static Logger log = Logger.getLogger(App.class)

    static void main(String[] args) {
        log.warn "started App.main()"
        SomeServiceClassJava.doLogging()
        SomeServiceClassGroovy.doLogging()
        Marker CRASH_NIT = new MarkerManager.Log4jMarker("MARKER");
        log.fatal("fatal");
        log.error("error");
        log.warn("warn");
        log.info("info");
        log.debug("debug")
        log.trace("trace")

        log.trace(CRASH_NIT, "trace with MARKER")
        log.info "finished App.main()"
    }
}
