/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package bel.log4j.bug

import spock.lang.Specification

class AppTest extends Specification {

    def "logger"() {
        setup:
        def app = new SomeServiceClassGroovy()

        when:
        0 == 0
        //def result = app.greeting

        then:
        1 == 1
        //result != null
    }

}
